# Generated by Django 4.0.1 on 2022-01-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_movie_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='booked',
            field=models.BooleanField(default=False),
        ),
    ]
